version: '3.8'

services:
  backend:
    image: ritesh0419/todo-backend:latest
    restart: always
    build: ./todo-docker-jenkins/backend
    ports:
      - "5000:5000"
    networks:
      - todo_network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:${MONGO_PORT}/${DB_NAME}

  frontend:
    image: ritesh0419/todo-frontend:latest
    restart: always
    build: ./todo-docker-jenkins/frontend
    ports:
      - "5173:5173"
    networks:
      - todo_network

  mongodb:
    image: mongo:4.4
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - todo_network
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  sonarqube:
    image: sonarqube:lts-community
    container_name: SonarQube-Server
    restart: always
    ports:
      - "9000:9000"
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  mongo-data:
    driver: local



# version: '3.8'

# services:
#   backend:
#     image: ritesh0419/todo-backend:latest
#     restart: always
#     build: ./todo-docker-jenkins/backend
#     ports:
#       - "5000:5000"
#     networks:
#       - todo_network
#     depends_on:
#       - mongodb
#     environment:
#       - MONGO_URL=mongodb://mongodb:${MONGO_PORT}/${DB_NAME}

#   frontend:
#     image: ritesh0419/todo-frontend:latest
#     restart: always
#     build: ./todo-docker-jenkins/frontend
#     ports:
#       - "5173:5173"
#     networks:
#       - todo_network

#   mongodb:
#     image: mongo:4.4
#     restart: always
#     ports:
#       - "${MONGO_PORT}:${MONGO_PORT}"
#     networks:
#       - todo_network
#     volumes:
#       - mongo-data:/data/db
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
#       - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}



# networks:
#   todo_network:
#     driver: bridge

# volumes:
#   mongo-data:
#     driver: local
  

