version: '3.8'

services:
  backend:
    image: ritesh0419/todo-backend:latest
    restart: always
    build: ./todo-docker-jenkins/backend
    ports:
      - "5000:5000"
    networks:
      - todo_network
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:${MONGO_PORT}/${DB_NAME}

  frontend:
    image: ritesh0419/todo-frontend:latest
    restart: always
    build: ./todo-docker-jenkins/frontend
    ports:
      - "5173:5173"
    networks:
      - todo_network

  mongodb:
    image: mongo:4.4
    restart: always
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    networks:
      - todo_network
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - todo_network

  # sonarqube:
  #     image: sonarqube:lts-community
  #     container_name: SonarQube-Server
  #     restart: always
  #     ports:
  #       - "9000:9000"
  #     networks:
  #       - todo_network
  #     volumes:
  #       - sonarqube_data:/opt/sonarqube/data
  #       - sonarqube_extensions:/opt/sonarqube/extensions
  #       - sonarqube_logs:/opt/sonarqube/logs
      
  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   restart: always
  #   volumes:
  #     - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
  #   ports:
  #     - "9090:9090"
  #   networks:
  #     - todo_network
        
  # grafana:
  #   image: grafana/grafana
  #   container_name: grafana
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - todo_network
  #   volumes:
  #     - grafana-storage:/var/lib/grafana

  # node-exporter:
  #   image: prom/node-exporter
  #   container_name: node-exporter
  #   restart: always
  #   ports:
  #     - "9100:9100"
  #   networks:
  #     - todo_network

networks:
  todo_network:
    driver: bridge

volumes:
  mongo-data:
  # grafana-storage:
  # sonarqube_data:
  # sonarqube_extensions:
  # sonarqube_logs:



# version: '3.8'

# services:
#   backend:
#     image: ritesh0419/todo-backend:latest
#     restart: always
#     build: ./todo-docker-jenkins/backend
#     ports:
#       - "5000:5000"
#     networks:
#       - todo_network
#     depends_on:
#       - mongodb
#     environment:
#       - MONGO_URL=mongodb://mongodb:${MONGO_PORT}/${DB_NAME}

#   frontend:
#     image: ritesh0419/todo-frontend:latest
#     restart: always
#     build: ./todo-docker-jenkins/frontend
#     ports:
#       - "5173:5173"
#     networks:
#       - todo_network

#   mongodb:
#     image: mongo:4.4
#     restart: always
#     ports:
#       - "${MONGO_PORT}:${MONGO_PORT}"
#     networks:
#       - todo_network
#     volumes:
#       - mongo-data:/data/db
#     environment:
#       - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
#       - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}



# networks:
#   todo_network:
#     driver: bridge

# volumes:
#   mongo-data:
#     driver: local
  

